export { default as App } from '../src/App'
export { default as ProductDetail } from '../src/ProductDetail'
export { default as CompareView } from '../src/CompareView'
export { default as SwitchFlow } from '../src/SwitchFlow'
export { fetchCatalog } from '../src/api'
export * from '../src/analytics'
export * from '../src/navigation-state'
// SWITCH session regressions exercise App-level persistence and history helpers through this test entry.
export * from '../src/switch-session'
export * from '../src/preview-mode'
export { installDemoPreviewFetch } from '../src/demo-preview'
export { installRealVisualPreviewFetch } from '../src/real-visual-preview'
export { installStressPreviewFetch } from '../src/stress-preview'
