import type { CatalogProduct } from './api'

export function isRealVisualPreview(): boolean {
  return new URLSearchParams(window.location.search).get('realpreview') === '1'
}

const REAL_VISUAL_PRODUCTS: CatalogProduct[] = [
  {
    product_id: 'product_e7eb6b131871033e',
    brand: '로얄캐닌',
    canonical_name: '다이제스티브 케어',
    feed_type: '건식',
    life_stage: 'adult',
    display_image_url: 'https://marspetcareaprimocdn.petcare.global/00dd09d3-2929-406b-b022-b42400bc3cb9/00dd09d3-2929-406b-b022-b42400bc3cb9_DownloadAsJpg.jpg',
    representative_variant_id: null,
    representative_package_size_text: '2 kg',
    representative_package_weight_g: 2000,
    variant_count: 3,
    has_variants: true,
    ingredient_declaration_count: 0,
    full_ingredient_declaration_count: 0,
    has_ingredient_details: false,
    has_full_ingredient_declaration: false,
    nutrition_panel_count: 0,
    has_nutrition_details: false,
    manufacturing_observation_count: 0,
    has_manufacturing_details: false,
    manufacturing_country_codes: [],
    market_observation_count: 1,
    has_market_details: true,
    assessed_market_country_codes: ['KR'],
    current_market_country_codes: ['KR'],
    formula_match_market_country_codes: [],
    ingredient_term_result_count: 0,
    confirmed_present_ingredient_terms: [],
    direct_evidence_ingredient_terms: [],
    flavor_associated_ingredient_terms: [],
    reviewed_not_found_ingredient_terms: [],
    insufficient_evidence_ingredient_terms: [],
    official_targets: [],
    features: ['digestive'],
    recipe_families: [],
    recipe_details: [],
    official_recipe_traits: [],
  },
  {
    product_id: 'product_11b1d67652ba122e',
    brand: '오리젠',
    canonical_name: 'Six Fish',
    feed_type: '건식',
    life_stage: null,
    display_image_url: 'https://apac.orijenpetfoods.com/dw/image/v2/BFDW_PRD/on/demandware.static/-/Sites-orijen-ap-master-catalog/default/dwed49fb84/2023/Cat-2023/SIX%20FISH/ORIJEN%20Six%20Fish%20Cat%20Front%20Right%205.4kg%20APAC.png?sw=500',
    representative_variant_id: null,
    representative_package_size_text: '1.8 kg',
    representative_package_weight_g: 1800,
    variant_count: 2,
    has_variants: true,
    ingredient_declaration_count: 0,
    full_ingredient_declaration_count: 0,
    has_ingredient_details: false,
    has_full_ingredient_declaration: false,
    nutrition_panel_count: 0,
    has_nutrition_details: false,
    manufacturing_observation_count: 1,
    has_manufacturing_details: true,
    manufacturing_country_codes: ['CA'],
    market_observation_count: 1,
    has_market_details: true,
    assessed_market_country_codes: ['KR'],
    current_market_country_codes: ['KR'],
    formula_match_market_country_codes: [],
    ingredient_term_result_count: 0,
    confirmed_present_ingredient_terms: [],
    direct_evidence_ingredient_terms: [],
    flavor_associated_ingredient_terms: [],
    reviewed_not_found_ingredient_terms: [],
    insufficient_evidence_ingredient_terms: [],
    official_targets: [],
    features: [],
    recipe_families: ['fish'],
    recipe_details: [],
    official_recipe_traits: [],
  },
  {
    product_id: 'product_070ac10830254aa6',
    brand: '힐스',
    canonical_name: '어덜트 퍼펙트 다이제스천',
    feed_type: '건식',
    life_stage: 'adult',
    display_image_url: 'https://pvimages-prod.azureedge.net/6235253_p1.jpg',
    representative_variant_id: null,
    representative_package_size_text: '1.58 kg',
    representative_package_weight_g: 1580,
    variant_count: 1,
    has_variants: true,
    ingredient_declaration_count: 0,
    full_ingredient_declaration_count: 0,
    has_ingredient_details: false,
    has_full_ingredient_declaration: false,
    nutrition_panel_count: 0,
    has_nutrition_details: false,
    manufacturing_observation_count: 1,
    has_manufacturing_details: true,
    manufacturing_country_codes: ['US'],
    market_observation_count: 1,
    has_market_details: true,
    assessed_market_country_codes: ['KR'],
    current_market_country_codes: ['KR'],
    formula_match_market_country_codes: [],
    ingredient_term_result_count: 0,
    confirmed_present_ingredient_terms: [],
    direct_evidence_ingredient_terms: [],
    flavor_associated_ingredient_terms: [],
    reviewed_not_found_ingredient_terms: [],
    insufficient_evidence_ingredient_terms: [],
    official_targets: [],
    features: ['digestive'],
    recipe_families: [],
    recipe_details: [],
    official_recipe_traits: [],
  },
  {
    product_id: 'product_59ca36b8107f5547',
    brand: '지위픽',
    canonical_name: '지위픽 에어드라이 고등어&양고기 캣',
    feed_type: '건식',
    life_stage: 'all_life_stages',
    display_image_url: 'https://www.ziwipets.co.kr/data/goods/88/CAT_Mackerel_Lamb_400G.jpg',
    representative_variant_id: null,
    representative_package_size_text: '400 g',
    representative_package_weight_g: 400,
    variant_count: 2,
    has_variants: true,
    ingredient_declaration_count: 0,
    full_ingredient_declaration_count: 0,
    has_ingredient_details: false,
    has_full_ingredient_declaration: false,
    nutrition_panel_count: 0,
    has_nutrition_details: false,
    manufacturing_observation_count: 1,
    has_manufacturing_details: true,
    manufacturing_country_codes: ['NZ'],
    market_observation_count: 1,
    has_market_details: true,
    assessed_market_country_codes: ['KR'],
    current_market_country_codes: ['KR'],
    formula_match_market_country_codes: [],
    ingredient_term_result_count: 0,
    confirmed_present_ingredient_terms: [],
    direct_evidence_ingredient_terms: [],
    flavor_associated_ingredient_terms: [],
    reviewed_not_found_ingredient_terms: [],
    insufficient_evidence_ingredient_terms: [],
    official_targets: [],
    features: [],
    recipe_families: ['fish', 'meat'],
    recipe_details: ['mackerel', 'lamb'],
    official_recipe_traits: [],
  },
  {
    product_id: 'product_4565e849aa0259d0',
    brand: 'Purina Pro Plan',
    canonical_name: '프로플랜 캣 성묘용 연어',
    feed_type: '건식',
    life_stage: 'adult',
    display_image_url: 'https://images.pet-friends.co.kr/storage/pet_friends/product/id/2/d/2/b/5/f/c/2d2b5fc7e81c84eadbe0828f3200ed82/10000/e149fa2d073f9168d7a39f59e2b20c7a.jpeg',
    representative_variant_id: null,
    representative_package_size_text: '1.5 kg',
    representative_package_weight_g: 1500,
    variant_count: 2,
    has_variants: true,
    ingredient_declaration_count: 0,
    full_ingredient_declaration_count: 0,
    has_ingredient_details: false,
    has_full_ingredient_declaration: false,
    nutrition_panel_count: 0,
    has_nutrition_details: false,
    manufacturing_observation_count: 1,
    has_manufacturing_details: true,
    manufacturing_country_codes: ['AU'],
    market_observation_count: 1,
    has_market_details: true,
    assessed_market_country_codes: ['KR'],
    current_market_country_codes: ['KR'],
    formula_match_market_country_codes: [],
    ingredient_term_result_count: 0,
    confirmed_present_ingredient_terms: [],
    direct_evidence_ingredient_terms: [],
    flavor_associated_ingredient_terms: [],
    reviewed_not_found_ingredient_terms: [],
    insufficient_evidence_ingredient_terms: [],
    official_targets: [],
    features: [],
    recipe_families: ['fish'],
    recipe_details: ['salmon'],
    official_recipe_traits: [],
  },
  {
    product_id: 'product_d39b911c9303664f',
    brand: 'Feline Natural',
    canonical_name: '치킨&램 피스트',
    feed_type: '습식',
    life_stage: 'all_life_stages',
    display_image_url: 'https://cdn.shoplightspeed.com/shops/641236/files/32882862/k9-natural-feline-natural-cat-can-chicken-lamb-fea.jpg',
    representative_variant_id: null,
    representative_package_size_text: '85 g',
    representative_package_weight_g: 85,
    variant_count: 2,
    has_variants: true,
    ingredient_declaration_count: 0,
    full_ingredient_declaration_count: 0,
    has_ingredient_details: false,
    has_full_ingredient_declaration: false,
    nutrition_panel_count: 0,
    has_nutrition_details: false,
    manufacturing_observation_count: 1,
    has_manufacturing_details: true,
    manufacturing_country_codes: ['NZ'],
    market_observation_count: 1,
    has_market_details: true,
    assessed_market_country_codes: ['KR'],
    current_market_country_codes: ['KR'],
    formula_match_market_country_codes: [],
    ingredient_term_result_count: 0,
    confirmed_present_ingredient_terms: [],
    direct_evidence_ingredient_terms: [],
    flavor_associated_ingredient_terms: [],
    reviewed_not_found_ingredient_terms: [],
    insufficient_evidence_ingredient_terms: [],
    official_targets: [],
    features: [],
    recipe_families: ['poultry', 'meat'],
    recipe_details: ['chicken', 'lamb'],
    official_recipe_traits: [],
  },
]

export function installRealVisualPreviewFetch(): void {
  if (!isRealVisualPreview()) return

  document.documentElement.dataset.realVisualPreview = 'true'
  const style = document.createElement('style')
  style.textContent = `
    html[data-real-visual-preview='true'] body::after {
      content: '실제품 UI 테스트';
      position: fixed;
      right: 14px;
      bottom: 14px;
      z-index: 10000;
      border: 1px solid rgba(24,24,27,.18);
      padding: 6px 8px;
      background: rgba(255,255,255,.94);
      color: #343439;
      font-size: 10px;
      font-weight: 750;
      pointer-events: none;
    }
  `
  document.head.appendChild(style)

  const nativeFetch = window.fetch.bind(window)
  window.fetch = async (input: RequestInfo | URL, init?: RequestInit) => {
    const requestUrl = input instanceof Request ? input.url : input.toString()
    const url = new URL(requestUrl, window.location.href)
    const view = url.pathname.split('/').filter(Boolean).at(-1)

    if (view !== 'effective_product_catalog_summary') return nativeFetch(input, init)
    if (init?.signal?.aborted) throw new DOMException('The operation was aborted.', 'AbortError')

    return new Response(JSON.stringify(REAL_VISUAL_PRODUCTS), {
      status: 200,
      headers: { 'Content-Type': 'application/json; charset=utf-8' },
    })
  }
}
